### PR TITLE
feature: support for jbangargs

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by jponge** [comment]
This is useful for the things I'm doing in https://github.com/smallrye/smallrye-mutiny/pull/519

**Comment by gastaldi** [comment]
That looks good, but maybe we should name it `jbangargs` to match the nomenclature used in https://github.com/jbangdev/jbang-action

**Comment by gastaldi** [comment]
Also the commit needs to follow semantic versioning rules: something like `feature: support for jbangargs`

**Comment by maxandersen** [comment]
Nice. Yes would be nice have same name for these - I see https://github.com/jbangdev/jbang-gradle-plugin miss it too....but here it would be jbang.jbangargs but I guess that fits :)

**Comment by jponge** [comment]
There you go!

I wonder why the "semantic pull request" action complains though.

**Comment by gastaldi** [comment]
@jponge thanks! 

Now we wait for @maxandersen to release this plugin (as 0.1.0) :)

**Comment by jponge** [comment]
Great :-) 

The sooner, the better!

**Comment by maxandersen** [comment]
I released 0.0.7 after adding docs for this.

**Comment by jponge** [comment]
Great thanks @maxandersen

**Pull request merged**
