### PR TITLE
fix: Lowering the minimum Maven version requirement

### PR DESCRIPTION
**Pull request by rsvoboda**
Lowering the minimum Maven version requirement to 3.6.0 to be in sync with `maven-plugin-annotations` and `maven-plugin-plugin`

Initiated via https://github.com/quarkusio/quarkus/pull/13128.

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]

**Comment by gastaldi** [comment]
Good catch! Thanks! @maxandersen can you cut a release?

EDIT: Nevermind, already did (forgot it was that easy)

EDIT 2: Build failed. Artifacts not signed, will investigate tomorrow

**Comment by rsvoboda** [comment]
@gastaldi  Please let me know once the release is done so I can adjust my quarkus PR

**Comment by gastaldi** [comment]
Apparently I don't have enough permission to release it (I tried to do it locally but got Forbidden)

**Comment by gastaldi** [comment]
@maxandersen can you perform the release?

**Comment by maxandersen** [comment]
damn - missed this notification :/ now released!

**Comment by maxandersen** [comment]
we really need to get tag action to do a `mvn -Drelease deploy`

**Pull request merged**
